### Test GET /api/v1/tickers (Get All Tickers)
GET http://localhost:3000/api/v1/tickers
Accept: application/json
Authorization: Bearer <your_token_here>

###

### Test GET /api/v1/tickers (Get All Tickers)
GET http://localhost:8963/api/v1/tickers/6782017fe6489b08833fd4ee
Accept: application/json

###

### Test POST /api/v1/tickers (Add New Ticker)
POST http://localhost:3000/api/v1/tickers
Content-Type: application/json
Accept: application/json
Authorization: Bearer <your_token_here>

{
  "name": "AAPL",
  "companyName": "Apple Inc.",
  "price": 150.00,
  "exchange": "NASDAQ",
  "currency": "USD",
  "industry": "Technology"
}

###

### Test PUT /api/v1/tickers/:id (Update Ticker)
PUT http://localhost:8963/api/v1/tickers/6782017fe6489b08833fd4ee
Content-Type: application/json
Accept: application/json

###

### Test DELETE /api/v1/tickers/:id (Delete Ticker)
DELETE http://localhost:3000/api/v1/tickers/1
Authorization: Bearer <your_token_here>

###
